# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# import pymysql
import re
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QWidget, QMessageBox
import pymysql


def checkmessage(username,mail,password1,password2):
    if not username:
        return "用户名不能为空"
    elif not mail:
        return "邮箱不能为空"
    elif not password1:
        return "密码不能为空"
    elif not password2:
        return "确认密码不能为空"


    if password1 != password2:
        return '前后密码不一致，请重新输入'

    pattern = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
    if not re.match(pattern, mail):
        return '邮箱格式不正确，请重新输入'



    # 1.链接数据库
    conn = pymysql.connect(host="127.0.0.1", port=3306, user='root', password='520520hxa', charset='utf8',
                           db='zhuochong2333')
    cursor = conn.cursor(cursor=pymysql.cursors.DictCursor)

    # 2.发送指令

    sql = "select * from login"
    cursor.execute(sql)
    list1 = cursor.fetchall()
    if list1:
        print(list1)


    for item in list1:
        if item['username'] == username:
            return '该用户名已被注册，请换一个名称'

    # 3.关闭链接
    cursor.close()
    conn.close()

    return 'ok'


def sql_insert(username, mail, password1):
    # 1.链接数据库
    conn = pymysql.connect(host="127.0.0.1", port=3306, user='root', password='520520hxa', charset='utf8',
                           db='zhuochong2333')
    cursor = conn.cursor(cursor=pymysql.cursors.DictCursor)

    # 2.发送指令

    sql = "insert into login(username,mail,password) values(%s,%s,%s)"   # 将我们用户前端输入的内容放到我们的数据库中保存下来的指令，其中%s就是字符串的代替形式，学习python后就有更深刻理解
    cursor.execute(sql, [username, mail, password1])              # 将用户输入信息放到数据库中
    conn.commit()


    # 3.关闭链接
    cursor.close()
    conn.close()

    return '注册成功'





class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(798, 438)
        Form.setStyleSheet("background-color: #faf2f5")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 0, 661, 431))
        # self.label_2.setStyleSheet("border-image: url(:/img/rumia.png);\n"
        self.label_2.setStyleSheet("border-image: url(:/图片/rumia.png);\n"
"")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(310, 70, 91, 71))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(31)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color :#f56692")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(310, 130, 311, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: #7e8490")
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(300, 180, 211, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("border-radius:3px;\n"
"color:#7e8490;\n"
"border: 1px solid #7e8490;")
        self.lineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit.setDragEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(540, 180, 201, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("border-radius:3px;\n"
"color:#7e8490;\n"
"border: 1px solid #7e8490;")
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_2.setDragEnabled(False)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(300, 240, 211, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("border-radius:3px;\n"
"color:#7e8490;\n"
"border: 1px solid #7e8490;")
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_3.setDragEnabled(False)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(540, 240, 201, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("border-radius:3px;\n"
"color:#7e8490;\n"
"border: 1px solid #7e8490;")
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_4.setDragEnabled(False)
        self.lineEdit_4.setObjectName("lineEdit_4")

        self.pushButton_1 = QtWidgets.QPushButton(Form)
        self.pushButton_1.setGeometry(QtCore.QRect(570, 300, 171, 31))

        # self.label_5 = QtWidgets.QLabel(Form)
        # self.label_5.setGeometry(QtCore.QRect(570, 300, 171, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)

        self.pushButton_1.setFont(font)
        self.pushButton_1.setStyleSheet("color: #f6769d;\n"
                                        "border: none;\n")

        self.pushButton_1.setObjectName("pushButton_1")

        # self.label_5.setFont(font)
        # self.label_5.setStyleSheet("color: #f6769d")
        # self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(360, 380, 311, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color: #ffffff;\n"
"background-color: #f6769d;\n"
"border: none;\n"
"border-radius: 2px ")

        self.pushButton.setObjectName("pushButton")

        self.pushButton.clicked.connect(self.pushButton_clicked)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "注册"))
        self.label_4.setText(_translate("Form", "期待与你在桌宠的邂逅"))
        self.lineEdit.setPlaceholderText(_translate("Form", "  用户名"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "  邮箱"))
        self.lineEdit_3.setPlaceholderText(_translate("Form", " 密码"))
        self.lineEdit_4.setPlaceholderText(_translate("Form", " 再次输入密码"))
        self.pushButton_1.setText(_translate("Form", "已有账号？登录"))

        # self.label_5.setText(_translate("Form", "已有账号？登录"))


        self.pushButton.setText(_translate("Form", "注册"))

    def alert(self,msg):
        self.error_box = QMessageBox()
        self.error_box.setIcon(QMessageBox.Warning)
        self.error_box.setWindowTitle("错误提示")
        self.error_box.setText(msg)
        self.error_box.exec_()

    def pushButton_clicked(self):
        username = self.lineEdit.text()
        mail = self.lineEdit_2.text()
        password1 = self.lineEdit_3.text()
        password2 = self.lineEdit_4.text()
        msg = checkmessage(username=username, mail=mail, password1=password1, password2=password2)
        if msg != 'ok':
            # 创建错误提示弹窗
            self.alert(msg)
        else:
            msg = sql_insert(username, mail, password1)
            error_box = QMessageBox()
            error_box.setIcon(QMessageBox.Warning)
            error_box.setWindowTitle("注册成功")
            error_box.setText(msg)
            error_box.exec_()
            self.close()


class RegisterWindow(QWidget, Ui_Form):
    def __init__(self):
        super().__init__()
        self.setWindowTitle('注册页面')
        self.setupUi(self)


if __name__ == "__main__":

    # from mains import MainWindow
    # app = QApplication([])
    # main_window = MainWindow()
    # main_window.show()
    # app.exec_()

    app = QApplication([])
    main_window = RegisterWindow()
    main_window.show()
    app.exec_()
