# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled_222.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5.QtWidgets import QApplication, QWidget, QLabel, QLineEdit, QPushButton, QVBoxLayout, QHBoxLayout, QSizePolicy, QFrame, QMessageBox

# from VoiceSettingUI import get_latest_pet_sound
from PyQt5 import QtCore, QtGui, QtWidgets

from PyQt5.QtCore import Qt, QThread, pyqtSignal

from hashlib import md5
import random,requests
from multiprocessing import Process


from PyQt5 import QtCore, QtGui, QtWidgets
import os

class Ui_Form(object):
    def setupUi(self, Form):
        current_dir = os.path.dirname(__file__)
        self.current_dir_str = str(current_dir)
        Form.setObjectName("Form")
        Form.resize(1216, 871)
        Form.setMaximumSize(QtCore.QSize(1800, 1500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(self.current_dir_str + "/UI_pic/登入.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("background:rgb(255, 255, 255)")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1201, 841))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMaximumSize(QtCore.QSize(1800, 1500))
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(0, 170, 295, 661))
        self.frame_3.setStyleSheet("border: 2px solid black;\n"
"border-right:0.5px solid black;\n"
"background:rgb(245,245,245)")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_9 = QtWidgets.QLabel(self.frame_3)
        self.label_9.setGeometry(QtCore.QRect(10, 20, 271, 21))
        self.label_9.setStyleSheet("border: 2px solid rgb(211, 211, 211);\n"
"border: 0px solid black;\n"
"font: 12pt \"Agency FB\";")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.toolButton_6 = QtWidgets.QToolButton(self.frame_3)
        self.toolButton_6.setGeometry(QtCore.QRect(160, 580, 111, 31))
        self.toolButton_6.setMaximumSize(QtCore.QSize(200, 80))
        self.toolButton_6.setStyleSheet("border:2px solid;\n"
"font: 15pt \"Agency FB\";\n"
"background:#99CCFF;\n"
"border-radius:10px;")
        self.toolButton_6.setObjectName("toolButton_6")
        self.label_8 = QtWidgets.QLabel(self.frame_3)
        self.label_8.setGeometry(QtCore.QRect(20, 590, 120, 51))
        self.label_8.setStyleSheet("\n"
"border: 0px solid black;\n"
"font: 15pt \"Bahnschrift SemiCondensed\";\n"
"color:#1098ad;")
        self.label_8.setObjectName("label_8")
        self.frame_12 = QtWidgets.QFrame(self.frame_3)
        self.frame_12.setGeometry(QtCore.QRect(10, 460, 270, 85))
        self.frame_12.setMaximumSize(QtCore.QSize(450, 16777215))
        self.frame_12.setStyleSheet("border: 2px solid black;\n"
"font: 18pt \"Agency FB\";\n"
"background:rgb(1, 119, 169);\n"
"border-radius:10px;\n"
"")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.label_3 = QtWidgets.QLabel(self.frame_12)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 65, 65))
        self.label_3.setMaximumSize(QtCore.QSize(65, 65))
        self.label_3.setStyleSheet("border: 0px solid black;")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(self.current_dir_str + "/UI_pic/对话.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.toolButton = QtWidgets.QToolButton(self.frame_12)
        self.toolButton.setGeometry(QtCore.QRect(80, 10, 180, 65))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(25)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.toolButton.setFont(font)
        self.toolButton.setStyleSheet("font:bold 25pt \"微软雅黑\";\n"
"\n"
"border: 0px solid black;\n"
"color:#ffffff;\n"
"\n"
"")
        self.toolButton.setObjectName("toolButton")
        self.frame_8 = QtWidgets.QFrame(self.frame_3)
        self.frame_8.setGeometry(QtCore.QRect(10, 360, 270, 85))
        self.frame_8.setStyleSheet("border: 2px solid black;\n"
"font: 18pt \"Agency FB\";\n"
"background:rgb(1, 119, 169);\n"
"border-radius:10px;\n"
"")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_4 = QtWidgets.QLabel(self.frame_8)
        self.label_4.setGeometry(QtCore.QRect(10, 15, 61, 61))
        self.label_4.setMaximumSize(QtCore.QSize(65, 65))
        self.label_4.setStyleSheet("border: 0px solid black;")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(self.current_dir_str + "/UI_pic/图片识别.png"))

        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.toolButton_5 = QtWidgets.QToolButton(self.frame_8)
        self.toolButton_5.setGeometry(QtCore.QRect(80, 11, 180, 65))
        self.toolButton_5.setMaximumSize(QtCore.QSize(180, 80))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(25)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.toolButton_5.setFont(font)
        self.toolButton_5.setStyleSheet("font:bold 25pt \"微软雅黑\";\n"
"\n"
"border: 0px solid black;\n"
"color:#ffffff;\n"
"\n"
"\n"
"")
        self.toolButton_5.setObjectName("toolButton_5")
        self.frame_11 = QtWidgets.QFrame(self.frame_3)
        self.frame_11.setGeometry(QtCore.QRect(10, 60, 270, 85))
        self.frame_11.setStyleSheet("border: 2px solid black;\n"
"font: 18pt \"Agency FB\";\n"
"background:rgb(1, 119, 169);\n"
"border-radius:10px;\n"
"")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.toolButton_2 = QtWidgets.QToolButton(self.frame_11)
        self.toolButton_2.setGeometry(QtCore.QRect(80, 11, 180, 65))
        self.toolButton_2.setMaximumSize(QtCore.QSize(180, 80))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(25)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.toolButton_2.setFont(font)
        self.toolButton_2.setStyleSheet("font:bold 25pt \"微软雅黑\";\n"
"\n"
"border: 0px solid black;\n"
"color:#ffffff;\n"
"\n"
"")
        self.toolButton_2.setObjectName("toolButton_2")
        self.label_7 = QtWidgets.QLabel(self.frame_11)
        self.label_7.setGeometry(QtCore.QRect(10, 13, 65, 65))
        self.label_7.setStyleSheet("border: 0px solid black;")
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(self.current_dir_str+"/UI_pic/1翻译.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.frame_10 = QtWidgets.QFrame(self.frame_3)
        self.frame_10.setGeometry(QtCore.QRect(10, 160, 270, 85))
        self.frame_10.setStyleSheet("border: 2px solid black;\n"
"font: 18pt \"Agency FB\";\n"
"background:rgb(1, 119, 169);\n"
"border-radius:10px;\n"
"")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.label_6 = QtWidgets.QLabel(self.frame_10)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 65, 65))
        self.label_6.setMaximumSize(QtCore.QSize(65, 65))
        self.label_6.setStyleSheet("border: 0px solid black;")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(self.current_dir_str + "/UI_pic/文件2.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.toolButton_3 = QtWidgets.QToolButton(self.frame_10)
        self.toolButton_3.setGeometry(QtCore.QRect(80, 11, 180, 65))
        self.toolButton_3.setMaximumSize(QtCore.QSize(180, 80))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(25)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.toolButton_3.setFont(font)
        self.toolButton_3.setStyleSheet("font:bold 25pt \"微软雅黑\";\n"
"\n"
"border: 0px solid black;\n"
"color:#ffffff;\n"
"\n"
"")
        self.toolButton_3.setObjectName("toolButton_3")
        self.frame_9 = QtWidgets.QFrame(self.frame_3)
        self.frame_9.setGeometry(QtCore.QRect(10, 260, 270, 85))
        self.frame_9.setStyleSheet("border: 2px solid black;\n"
"font: 18pt \"Agency FB\";\n"
"background:rgb(1, 119, 169);\n"
"border-radius:10px;\n"
"")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label_5 = QtWidgets.QLabel(self.frame_9)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 65, 65))
        self.label_5.setMaximumSize(QtCore.QSize(65, 65))
        self.label_5.setStyleSheet("border: 0px solid black;")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(self.current_dir_str + "/UI_pic/传输 (2).png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.toolButton_4 = QtWidgets.QToolButton(self.frame_9)
        self.toolButton_4.setGeometry(QtCore.QRect(80, 11, 180, 65))
        self.toolButton_4.setMaximumSize(QtCore.QSize(180, 80))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(25)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.toolButton_4.setFont(font)
        self.toolButton_4.setStyleSheet("font:bold 25pt \"微软雅黑\";\n"
"\n"
"border: 0px solid black;\n"
"color:#ffffff;\n"
"\n"
"\n"
"\n"
"")
        self.toolButton_4.setObjectName("toolButton_4")
        self.toolButton_8 = QtWidgets.QToolButton(self.frame_3)
        self.toolButton_8.setGeometry(QtCore.QRect(160, 620, 111, 31))
        self.toolButton_8.setStyleSheet("border:2px solid;\n"
"font: 15pt \"Agency FB\";\n"
"background:#99CCFF;\n"
"border-radius:10px;")
        self.toolButton_8.setObjectName("toolButton_8")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame)
        self.stackedWidget.setGeometry(QtCore.QRect(290, 170, 911, 661))
        self.stackedWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.stackedWidget.setMaximumSize(QtCore.QSize(16777215, 850))
        self.stackedWidget.setStyleSheet("border: 1px solid black;\n"
"border-top:0.5px solid;\n"
"bordground:rgb(251,251,251)\n"
"\n"
"\n"
"")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_0 = QtWidgets.QWidget()
        self.page_0.setStyleSheet("bordground:rgb(251,251,251)")
        self.page_0.setObjectName("page_0")
        self.pushButton_3 = QtWidgets.QPushButton(self.page_0)
        self.pushButton_3.setGeometry(QtCore.QRect(429, 300, 50, 50))
        self.pushButton_3.setStyleSheet("border-left:1px solid;\n"
"border-radius:25px;")
        self.pushButton_3.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(self.current_dir_str + "/UI_pic/交换.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_3.setObjectName("pushButton_3")
        self.comboBox_3 = QtWidgets.QComboBox(self.page_0)
        self.comboBox_3.setGeometry(QtCore.QRect(47, 100, 151, 51))
        self.comboBox_3.setStyleSheet("border-left:1px solid;\n"
"border-color:#1098ad;\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"font: 75 15pt \"微软雅黑\";")
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.textEdit_2 = QtWidgets.QTextEdit(self.page_0)
        self.textEdit_2.setGeometry(QtCore.QRect(44, 170, 411, 281))
        self.textEdit_2.setStyleSheet("border-left:1px solid;\n"
"border-color:#1098ad;\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"font: 16pt \"微软雅黑\";")
        self.textEdit_2.setObjectName("textEdit_2")
        self.comboBox_4 = QtWidgets.QComboBox(self.page_0)
        self.comboBox_4.setGeometry(QtCore.QRect(455, 100, 181, 51))
        self.comboBox_4.setStyleSheet("border-left:1px solid;\n"
"border-color:#1098ad;\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"font: 75 15pt \"微软雅黑\";")
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.page_0)
        self.textBrowser_5.setGeometry(QtCore.QRect(454, 170, 411, 281))
        self.textBrowser_5.setStyleSheet("border-left:1px solid;\n"
"border-color:#9b9b9b;\n"
"border-left-color:#1098ad;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"background:#e9e9ed;\n"
"font: 16pt \"微软雅黑\";")
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.toolButton_18 = QtWidgets.QToolButton(self.page_0)
        self.toolButton_18.setGeometry(QtCore.QRect(340, 470, 221, 61))
        self.toolButton_18.setStyleSheet("background:#faf2f5;\n"
"color:#f6769d;\n"
"font: 25pt \"Agency FB\";\n"
"border-radius:10px;")
        self.toolButton_18.setObjectName("toolButton_18")
        self.label_38 = QtWidgets.QLabel(self.page_0)
        self.label_38.setGeometry(QtCore.QRect(10, 540, 871, 41))
        self.label_38.setStyleSheet("font: 75 12pt \"微软雅黑\";\n"
"border: 0px solid black;")
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.textEdit_2.raise_()
        self.textBrowser_5.raise_()
        self.pushButton_3.raise_()
        self.comboBox_3.raise_()
        self.comboBox_4.raise_()
        self.toolButton_18.raise_()
        self.label_38.raise_()
        self.stackedWidget.addWidget(self.page_0)
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.comboBox = QtWidgets.QComboBox(self.page_1)
        self.comboBox.setGeometry(QtCore.QRect(140, 100, 150, 71))
        self.comboBox.setStyleSheet("font: 87 25pt \"Arial Black\";")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.page_1)
        self.comboBox_2.setGeometry(QtCore.QRect(570, 100, 151, 71))
        self.comboBox_2.setStyleSheet("font: 87 25pt \"Arial Black\";")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_12 = QtWidgets.QLabel(self.page_1)
        self.label_12.setGeometry(QtCore.QRect(370, 80, 121, 111))
        self.label_12.setStyleSheet("border: 0px solid black;")
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap(self.current_dir_str + "/UI_pic/导 (2).png"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.label_32 = QtWidgets.QLabel(self.page_1)
        self.label_32.setGeometry(QtCore.QRect(90, 300, 111, 40))
        self.label_32.setStyleSheet("border: 0px solid;\n"
"font: 75 18pt \"微软雅黑\";")
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.page_1)
        self.label_33.setGeometry(QtCore.QRect(90, 390, 111, 50))
        self.label_33.setStyleSheet("border: 0px solid;\n"
"font: 75 18pt \"微软雅黑\";")
        self.label_33.setObjectName("label_33")
        self.pushButton_4 = QtWidgets.QPushButton(self.page_1)
        self.pushButton_4.setGeometry(QtCore.QRect(220, 390, 491, 50))
        self.pushButton_4.setStyleSheet("font: 87 12pt \"Arial Black\";")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_34 = QtWidgets.QLabel(self.page_1)
        self.label_34.setGeometry(QtCore.QRect(110, 230, 681, 31))
        self.label_34.setStyleSheet("border: 0px solid black;")
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.pushButton_5 = QtWidgets.QPushButton(self.page_1)
        self.pushButton_5.setGeometry(QtCore.QRect(220, 300, 491, 50))
        self.pushButton_5.setStyleSheet("font: 87 12pt \"Arial Black\";")
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.toolButton_15 = QtWidgets.QToolButton(self.page_1)
        self.toolButton_15.setGeometry(QtCore.QRect(310, 490, 271, 71))
        self.toolButton_15.setStyleSheet("background:#faf2f5;\n"
"color:#f6769d;\n"
"font: 25pt \"Agency FB\";\n"
"border-radius:10px;")
        self.toolButton_15.setObjectName("toolButton_15")
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_13 = QtWidgets.QLabel(self.page_2)
        self.label_13.setGeometry(QtCore.QRect(50, 210, 121, 101))
        self.label_13.setStyleSheet("border: 0px solid black;")
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap(self.current_dir_str + "/UI_pic/文件发送.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.toolButton_16 = QtWidgets.QToolButton(self.page_2)
        self.toolButton_16.setGeometry(QtCore.QRect(60, 160, 101, 41))
        self.toolButton_16.setStyleSheet("border: 0px solid black;\n"
"font: 87 12pt \"Arial Black\";")
        self.toolButton_16.setObjectName("toolButton_16")
        self.toolButton_17 = QtWidgets.QToolButton(self.page_2)
        self.toolButton_17.setGeometry(QtCore.QRect(60, 370, 121, 41))
        self.toolButton_17.setStyleSheet("border: 0px solid black;\n"
"font: 87 12pt \"Arial Black\";")
        self.toolButton_17.setObjectName("toolButton_17")
        self.label_26 = QtWidgets.QLabel(self.page_2)
        self.label_26.setGeometry(QtCore.QRect(50, 420, 131, 101))
        self.label_26.setStyleSheet("border: 0px solid black;")
        self.label_26.setText("")
        self.label_26.setPixmap(QtGui.QPixmap(self.current_dir_str + "/UI_pic/文件接受.jpg"))
        self.label_26.setScaledContents(True)
        self.label_26.setObjectName("label_26")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.page_2)
        self.stackedWidget_2.setGeometry(QtCore.QRect(200, 130, 661, 461))
        self.stackedWidget_2.setStyleSheet("border: 1px solid black;\n"
"border-radius:10px;")
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_27 = QtWidgets.QLabel(self.page_3)
        self.label_27.setGeometry(QtCore.QRect(150, 60, 371, 271))
        self.label_27.setStyleSheet("border: 0px solid black;\n"
"font: 87 12pt \"Arial Black\";")
        self.label_27.setObjectName("label_27")
        self.stackedWidget_2.addWidget(self.page_3)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.toolButton_13 = QtWidgets.QToolButton(self.page_6)
        self.toolButton_13.setGeometry(QtCore.QRect(450, 30, 131, 61))
        self.toolButton_13.setStyleSheet("font: 20pt \"微软雅黑\";\n"
"border: 0px solid black;")
        self.toolButton_13.setObjectName("toolButton_13")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.page_6)
        self.lineEdit_2.setGeometry(QtCore.QRect(130, 20, 281, 30))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_29 = QtWidgets.QLabel(self.page_6)
        self.label_29.setGeometry(QtCore.QRect(50, 20, 60, 31))
        self.label_29.setStyleSheet("border: 0px solid black;\n"
"")
        self.label_29.setObjectName("label_29")
        self.label_28 = QtWidgets.QLabel(self.page_6)
        self.label_28.setGeometry(QtCore.QRect(50, 70, 61, 30))
        self.label_28.setStyleSheet("border: 0px solid black;\n"
"")
        self.label_28.setObjectName("label_28")
        self.pushButton = QtWidgets.QPushButton(self.page_6)
        self.pushButton.setGeometry(QtCore.QRect(130, 70, 281, 30))
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.page_6)
        self.textBrowser_4.setGeometry(QtCore.QRect(50, 120, 570, 320))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.stackedWidget_2.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.toolButton_14 = QtWidgets.QToolButton(self.page_7)
        self.toolButton_14.setGeometry(QtCore.QRect(400, 80, 191, 61))
        self.toolButton_14.setStyleSheet("font: 20pt \"微软雅黑\";\n"
"border: 0px solid black;")
        self.toolButton_14.setObjectName("toolButton_14")
        self.label_30 = QtWidgets.QLabel(self.page_7)
        self.label_30.setGeometry(QtCore.QRect(50, 100, 71, 30))
        self.label_30.setStyleSheet("border: 0px solid black;")
        self.label_30.setObjectName("label_30")
        self.pushButton_2 = QtWidgets.QPushButton(self.page_7)
        self.pushButton_2.setGeometry(QtCore.QRect(130, 100, 251, 30))
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.page_7)
        self.textBrowser_3.setGeometry(QtCore.QRect(50, 150, 570, 300))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.toolButton_12 = QtWidgets.QToolButton(self.page_7)
        self.toolButton_12.setGeometry(QtCore.QRect(50, 30, 121, 40))
        self.toolButton_12.setStyleSheet("background:#faf2f5;\n"
"color:#f6769d;\n"
"\n"
"font: 75 22pt \"微软雅黑\";\n"
"border-radius:10px;")
        self.toolButton_12.setObjectName("toolButton_12")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.page_7)
        self.textBrowser_2.setGeometry(QtCore.QRect(180, 30, 291, 40))
        self.textBrowser_2.setStyleSheet("font: 15pt \"微软雅黑\";\n"
"border-radius:5px;")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.stackedWidget_2.addWidget(self.page_7)
        self.label_39 = QtWidgets.QLabel(self.page_2)
        self.label_39.setGeometry(QtCore.QRect(10, 600, 871, 21))
        self.label_39.setStyleSheet("\n"
"border: 0px solid black;")
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.stackedWidget.addWidget(self.page_2)
        self.page3 = QtWidgets.QWidget()
        self.page3.setStyleSheet("")
        self.page3.setObjectName("page3")
        self.lineEdit = QtWidgets.QLineEdit(self.page3)
        self.lineEdit.setGeometry(QtCore.QRect(130, 100, 481, 41))
        self.lineEdit.setStyleSheet("border: 2px solid rgb(105, 178, 255)")
        self.lineEdit.setObjectName("lineEdit")
        self.label_14 = QtWidgets.QLabel(self.page3)
        self.label_14.setGeometry(QtCore.QRect(20, 280, 491, 331))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMaximumSize(QtCore.QSize(6000, 7000))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap(self.current_dir_str + "/UI_pic/ocr.jpeg"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.textEdit = QtWidgets.QTextEdit(self.page3)
        self.textEdit.setGeometry(QtCore.QRect(530, 280, 341, 331))
        self.textEdit.setStyleSheet("border: 2px solid black\n"
"")
        self.textEdit.setObjectName("textEdit")
        self.toolButton_9 = QtWidgets.QToolButton(self.page3)
        self.toolButton_9.setGeometry(QtCore.QRect(20, 100, 101, 41))
        self.toolButton_9.setObjectName("toolButton_9")
        self.toolButton_10 = QtWidgets.QToolButton(self.page3)
        self.toolButton_10.setGeometry(QtCore.QRect(620, 100, 251, 41))
        self.toolButton_10.setStyleSheet("border: 2px solid rgb(85, 255, 127);\n"
"font: 18pt \"Agency FB\";")
        self.toolButton_10.setObjectName("toolButton_10")
        self.label_15 = QtWidgets.QLabel(self.page3)
        self.label_15.setGeometry(QtCore.QRect(20, 250, 491, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("border: 0px solid black;\n"
"background:rgb(39, 39, 116);\n"
"font: 75 11pt \"微软雅黑\";\n"
"color: rgb(255, 255, 255)")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.label_35 = QtWidgets.QLabel(self.page3)
        self.label_35.setGeometry(QtCore.QRect(530, 250, 341, 31))
        self.label_35.setStyleSheet("border: 0px solid black;\n"
"background:rgb(39, 39, 116);\n"
"font: 75 11pt \"微软雅黑\";\n"
"color: rgb(255, 255, 255)")
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.page3)
        self.label_36.setGeometry(QtCore.QRect(10, 620, 871, 21))
        self.label_36.setStyleSheet("border: 0px solid black;")
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.page3)
        self.label_37.setGeometry(QtCore.QRect(240, 200, 391, 21))
        self.label_37.setStyleSheet("border: 0px solid black;")
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setObjectName("label_37")
        self.stackedWidget.addWidget(self.page3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setStyleSheet("bordground:rgb(251,251,251)")
        self.page_4.setObjectName("page_4")
        self.label_2 = QtWidgets.QLabel(self.page_4)
        self.label_2.setGeometry(QtCore.QRect(30, 20, 821, 21))
        self.label_2.setStyleSheet("border: 0px solid black;")
        self.label_2.setObjectName("label_2")
        self.label_10 = QtWidgets.QLabel(self.page_4)
        self.label_10.setGeometry(QtCore.QRect(110, 410, 180, 150))
        self.label_10.setStyleSheet("border: 0px solid black;")
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap(self.current_dir_str + "/UI_pic/yhj.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.label_16 = QtWidgets.QLabel(self.page_4)
        self.label_16.setGeometry(QtCore.QRect(360, 410, 161, 151))
        self.label_16.setStyleSheet("border: 0px solid black;")
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap(self.current_dir_str + "/UI_pic/dhh.png"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.page_4)
        self.label_17.setGeometry(QtCore.QRect(610, 410, 171, 151))
        self.label_17.setStyleSheet("border: 0px solid black;")
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap(self.current_dir_str + "/UI_pic/home.png"))
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.page_4)
        self.label_18.setGeometry(QtCore.QRect(240, 230, 421, 121))
        self.label_18.setStyleSheet("border: 0px solid black;\n"
"color:rgb(0, 85, 255);\n"
"font-weight: bold;\n"
"font: 75 italic 35pt \"Arial\"")
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.page_4)
        self.label_19.setGeometry(QtCore.QRect(140, 360, 591, 31))
        self.label_19.setStyleSheet("border: 0px solid black;\n"
"color:rgb(0, 85, 255);\n"
"font-weight: bold;")
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.page_4)
        self.label_20.setGeometry(QtCore.QRect(100, 570, 200, 50))
        self.label_20.setStyleSheet("border: 0px solid black;\n"
"font: 9pt \"Arial\";\n"
"")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.page_4)
        self.label_21.setGeometry(QtCore.QRect(140, 609, 200, 41))
        self.label_21.setStyleSheet("border: 0px solid black;\n"
"font: 9pt \"Arial\";\\n")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.page_4)
        self.label_22.setGeometry(QtCore.QRect(380, 570, 171, 50))
        self.label_22.setStyleSheet("border: 0px solid black;\n"
"font: 9pt \"Arial\";\n"
"")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.page_4)
        self.label_23.setGeometry(QtCore.QRect(420, 609, 131, 41))
        self.label_23.setStyleSheet("border: 0px solid black;\n"
"font: 9pt \"Arial\";\n"
"")
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.page_4)
        self.label_24.setGeometry(QtCore.QRect(630, 570, 171, 50))
        self.label_24.setStyleSheet("border: 0px solid black;\n"
"font: 9pt \"Arial\";\n"
"")
        self.label_24.setObjectName("label_24")
        self.textEdit_3 = QtWidgets.QTextEdit(self.page_4)
        self.textEdit_3.setGeometry(QtCore.QRect(80, 60, 741, 141))
        self.textEdit_3.setStyleSheet("border-radius:10px;")
        self.textEdit_3.setObjectName("textEdit_3")
        self.toolButton_11 = QtWidgets.QToolButton(self.page_4)
        self.toolButton_11.setGeometry(QtCore.QRect(740, 210, 81, 41))
        self.toolButton_11.setStyleSheet("border:0px solid;\n"
"\n"
"font: 75 14pt \"微软雅黑\";\n"
"background:#99CCFF;\n"
"border-radius:10px;")
        self.toolButton_11.setObjectName("toolButton_11")
        self.stackedWidget.addWidget(self.page_4)
        self.page = QtWidgets.QWidget()
        self.page.setStyleSheet("bordground:rgb(251,251,251);\n"
"border: 1px solid black;")
        self.page.setObjectName("page")
        self.scrollArea = QtWidgets.QScrollArea(self.page)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 901, 471))
        self.scrollArea.setStyleSheet("bordground:rgb(251,251,251);\n"
"border: 1px solid black;\n"
"border-bottom:0px solid")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 882, 2000))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(600, 2000))
        self.scrollAreaWidgetContents.setStyleSheet("border: 0px solid black;")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.textEdit_4 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.textEdit_4.setGeometry(QtCore.QRect(20, 20, 850, 2011))
        self.textEdit_4.setStyleSheet("font:bold 10pt \"微软雅黑\";\n"
"border: 0px solid black;\n"
"")
        self.textEdit_4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_4.setPlaceholderText("")
        self.textEdit_4.setObjectName("textEdit_4")
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_11.setGeometry(QtCore.QRect(270, 230, 401, 81))
        self.label_11.setStyleSheet("font:bold 25pt \"微软雅黑\";\n"
"color:rgb(194, 217, 255)")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.textEdit_5 = QtWidgets.QTextEdit(self.page)
        self.textEdit_5.setGeometry(QtCore.QRect(2, 500, 905, 161))
        self.textEdit_5.setStyleSheet("border: 2px solid;\n"
"border-radius:15px;\n"
"border-color:#1098ad;\n"
"font: 12pt \"Agency FB\";\n"
"background:#f5f5f7;\n"
"border-bottom:0px solid;\n"
"\n"
"border-bottom-left-radius:0px;\n"
"border-bottom-right-radius:0px;\n"
"")
        self.textEdit_5.setObjectName("textEdit_5")
        self.toolButton_19 = QtWidgets.QToolButton(self.page)
        self.toolButton_19.setGeometry(QtCore.QRect(750, 560, 90, 90))
        self.toolButton_19.setStyleSheet("border: 2px solid black;\n"
"font: 18pt \"Agency FB\";\n"
"background:#99CCFF;\n"
"border-radius:45px;\n"
"font-size:18px\n"
"")
        self.toolButton_19.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(self.current_dir_str + "/UI_pic/UP.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_19.setIcon(icon2)
        self.toolButton_19.setIconSize(QtCore.QSize(60, 60))
        self.toolButton_19.setObjectName("toolButton_19")
        self.stackedWidget.addWidget(self.page)
        self.textBrowser = QtWidgets.QTextBrowser(self.frame)
        self.textBrowser.setGeometry(QtCore.QRect(270, 0, 930, 161))
        self.textBrowser.setMinimumSize(QtCore.QSize(0, 0))
        self.textBrowser.setMaximumSize(QtCore.QSize(1200, 16777215))
        self.textBrowser.setStyleSheet("border: 0px solid;\n"
"\n"
"font: 12pt \"Agency FB\";\n"
"background:#f5f5f7;\n"
"border-color:#9b9b9b;\n"
"")
        self.textBrowser.setDocumentTitle("")
        self.textBrowser.setObjectName("textBrowser")
        self.toolButton_7 = QtWidgets.QToolButton(self.frame)
        self.toolButton_7.setGeometry(QtCore.QRect(1040, 60, 90, 90))
        self.toolButton_7.setMaximumSize(QtCore.QSize(300, 100))
        self.toolButton_7.setStyleSheet("border: 2px solid black;\n"
"font: 18pt \"Agency FB\";\n"
"background:#99CCFF;\n"
"border-radius:45px;\n"
"font-size:18px\n"
"")
        self.toolButton_7.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(self.current_dir_str + "/UI_pic/录音.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_7.setIcon(icon3)
        self.toolButton_7.setIconSize(QtCore.QSize(60, 60))
        self.toolButton_7.setObjectName("toolButton_7")

        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 0, 291, 161))
        # self.label.setGeometry(QtCore.QRect(0, 0, 500, 300))
        self.label.setStyleSheet("border: 0px solid black;\n"
"")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(self.current_dir_str + "/UI_pic/zhuochong_bangongicon.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_14.setBuddy(self.label_14)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(2)
        self.stackedWidget_2.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "智能办公桌宠服务平台"))
        self.label_9.setText(_translate("Form", "----智能桌宠服务平台欢迎您的使用----"))
        self.toolButton_6.setText(_translate("Form", "软件反馈"))
        self.label_8.setText(_translate("Form", "<html><head/><body><p>当前版本:<span style=\" font-weight:600;\">1.0  </span></p></body></html>"))
        self.toolButton.setText(_translate("Form", "文字对话"))
        self.toolButton_5.setText(_translate("Form", "OCR识别"))
        self.toolButton_2.setText(_translate("Form", "文本翻译"))
        self.toolButton_3.setText(_translate("Form", "类型转换"))
        self.toolButton_4.setText(_translate("Form", "文件传输"))
        self.toolButton_8.setText(_translate("Form", "产品解释"))
        self.comboBox_3.setItemText(0, _translate("Form", "选择源语言"))
        self.comboBox_3.setItemText(1, _translate("Form", "中文"))
        self.comboBox_3.setItemText(2, _translate("Form", "英语"))
        self.comboBox_3.setItemText(3, _translate("Form", "日语"))
        self.textEdit_2.setPlaceholderText(_translate("Form", "请输入想要翻译的内容!"))
        self.comboBox_4.setItemText(0, _translate("Form", "选择目标语言"))
        self.comboBox_4.setItemText(1, _translate("Form", "中文"))
        self.comboBox_4.setItemText(2, _translate("Form", "英语"))
        self.comboBox_4.setItemText(3, _translate("Form", "日语"))
        self.toolButton_18.setText(_translate("Form", "一键翻译"))
        self.label_38.setText(_translate("Form", "<html><head/><body><p>-------------------------------------支持<span style=\" font-weight:400; color:#000000;\">中、英、日</span>等当下热门语言互相翻译-------------------------------------</p></body></html>"))
        self.comboBox.setItemText(0, _translate("Form", "pdf"))
        self.comboBox.setItemText(1, _translate("Form", "image"))
        self.comboBox.setItemText(2, _translate("Form", "word"))
        self.comboBox_2.setItemText(0, _translate("Form", "pdf"))
        self.comboBox_2.setItemText(1, _translate("Form", "image"))
        self.comboBox_2.setItemText(2, _translate("Form", "word"))
        self.label_32.setText(_translate("Form", "文件路径："))
        self.label_33.setText(_translate("Form", "保存路径："))
        self.label_34.setText(_translate("Form", "免费在线转换器, 文件转换器 . 将PDF, 图像, 视频, 文档, 音频, 电子书及压缩等文件格式转换为其他格式。"))
        self.toolButton_15.setText(_translate("Form", "一键转换"))
        self.toolButton_16.setText(_translate("Form", "send模式"))
        self.toolButton_17.setText(_translate("Form", "receive模式"))
        self.label_27.setText(_translate("Form", "<html><head/><body><p align=\"center\"><br/></p><p>左侧可选择模式，‘send/service’。</p><p>如果你是发送文件方，你只需进入send模式！</p><p>如果你是文件接受方，你只需今日receive模式!</p><p>记得IP地址正确格式的输入哦！</p></body></html>"))
        self.toolButton_13.setText(_translate("Form", "开始发送"))
        self.label_29.setText(_translate("Form", "接收方IP："))
        self.label_28.setText(_translate("Form", "文件选择:"))
        self.textBrowser_4.setPlaceholderText(_translate("Form", "需接收方开启接收模式后，填写接收方IP，发送文件即可……"))
        self.toolButton_14.setText(_translate("Form", "开启接收状态"))
        self.label_30.setText(_translate("Form", "保存路径："))
        self.textBrowser_3.setPlaceholderText(_translate("Form", "开启接收状态后，告诉发送方‘我的IP’等待发送方传输……"))
        self.toolButton_12.setText(_translate("Form", "我的IP"))
        self.label_39.setText(_translate("Form", "---------------------------------------------------------远程文件快速传输，便利工作需求--------------------------------------------------------"))
        self.textEdit.setPlaceholderText(_translate("Form", "文字显示……"))
        self.toolButton_9.setText(_translate("Form", "选择文件"))
        self.toolButton_10.setText(_translate("Form", "开始识别"))
        self.label_15.setText(_translate("Form", "Image Preview"))
        self.label_35.setText(_translate("Form", "TextLabel"))
        self.label_36.setText(_translate("Form", "------------------------------------------------------------文字精准快速识别---------------------------------------------------------------"))
        self.label_37.setText(_translate("Form", "<html><head/><body><p>点击上方按钮选择图片，支持 <span style=\" font-size:12pt; font-weight:600; color:#ff0000;\">JPG/PNG/BMP/GIF/SVG</span> 格式</p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p>------------------------------------------------------------<span style=\" font-size:12pt; font-weight:600;\">在线反馈</span>---------------------------------------------------------------------------</p></body></html>"))
        self.label_18.setText(_translate("Form", "联系我们！！！"))
        self.label_19.setText(_translate("Form", "有任何疑问或者建议，请随时联系我们！您的想法对我们至关重要"))
        self.label_20.setText(_translate("Form", "邮箱： 295490xx2wd@wq.com"))
        self.label_21.setText(_translate("Form", "randomuser123@gmail.com"))
        self.label_22.setText(_translate("Form", "电话： (555) 123-4567"))
        self.label_23.setText(_translate("Form", "1224141624"))
        self.label_24.setText(_translate("Form", "地址：湖北省xx市桌宠有限公司"))
        self.textEdit_3.setPlaceholderText(_translate("Form", "请输入您的建议……"))
        self.toolButton_11.setText(_translate("Form", "提交"))
        self.label_11.setText(_translate("Form", "你好，我是你的智能助手！"))
        self.textEdit_5.setPlaceholderText(_translate("Form", "在这里输入文字吧……"))
        self.textBrowser.setMarkdown(_translate("Form", "  \n"
"\n"
"                                         **点击按钮打开语音助手** \n"
"\n"
""))
        self.textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Agency FB\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'sans-serif\'; color:#f6769d;\">  </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; color:#f6769d;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:36pt; font-weight:600; color:#f6769d;\">点击按钮打开语音助手 </span></p></body></html>"))


# class TranslateWindow(QWidget, Ui_Form):
#     def __init__(self):
#         super().__init__()
#         self.setWindowTitle('天气预报')
#         self.setupUi(self)
#
#     def closeEvent(self, event):
#         if self.voice_process and self.voice_process.is_alive():
#             self.voice_process.terminate()
#             self.voice_process.join()
#         event.ignore()  # 忽略默认的关闭事件
#         self.hide()  # 隐藏当前窗口，而不是关闭
#
#
#
#
#
# if __name__ == "__main__":
#
#     app = QApplication([])
#     main_window = TranslateWindow()
#     main_window.show()
#     app.exec_()
