# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tianqi.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys
from PyQt5.QtWidgets import QApplication, QWidget, QLabel, QLineEdit, QPushButton, QVBoxLayout, QHBoxLayout, QSizePolicy, QFrame

from VoiceSettingUI import get_latest_pet_sound
from PyQt5 import QtCore, QtGui, QtWidgets
default_city = '武汉'
from weather_api.QWeatherAPI import weather_seven
from PyQt5.QtCore import Qt, QThread, pyqtSignal
list1 = []
list1 = weather_seven(default_city)
print(list1)

class VoiceThread(QThread):
    character_name = get_latest_pet_sound()
    print(f'当前声音{character_name}')
    finished = pyqtSignal()

    def __init__(self, msg):
        super(VoiceThread, self).__init__()
        self.msg = msg

    def run(self):
        character_name = get_latest_pet_sound()
        print(f'当前声音{character_name}')
        from TTS_bachongshenzi import tts_and_play
        print(self.msg)
        tts_and_play(text=self.msg)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(729, 422)
        font = QtGui.QFont()
        font.setFamily("Dubai Light")
        Form.setFont(font)
        Form.setStyleSheet("\n"
"background-color: #316ea0\n"
"")

        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(20, 20, 191, 31))
        self.lineEdit.setStyleSheet("QLineEdit { \n"
"    border: 1px solid black;\n"
"    background-color:white;\n"
"    border-radius: 10%;\n"
" }")
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(210, 20, 31, 31))
        self.label.setStyleSheet("border-image: url(./weather_api/icon/search.png);\n"
"")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("./weather_api/icon/wifi.png"))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(240, 90, 54, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color : white")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(150, 90, 61, 61))
        self.label_4.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Javanese Text")
        font.setPointSize(40)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color : white;\n"
"")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(140, 160, 154, 21))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(13)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:white\n"
"")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(13)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:white\n"
"")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 121, 91))
        self.label_2.setStyleSheet("border-image: url(./weather_api/weather_img/多云.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(30, 240, 291, 16))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color:white")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(20, 280, 271, 121))
        self.label_8.setStyleSheet("background-color:#9c58fe;\n"
"border-radius:10%;")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(500, 0, 231, 61))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(19)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color:white")
        self.label_9.setObjectName("label_9")
        self.layoutWidget_2 = QtWidgets.QWidget(Form)
        self.layoutWidget_2.setGeometry(QtCore.QRect(340, 70, 371, 21))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_37 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_37.setFont(font)
        self.label_37.setStyleSheet("background-color:#09b4be;\n"
"border-radius:3px;\n"
"color:white;\n"
"")
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_4.addWidget(self.label_37)
        self.label_38 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_38.setFont(font)
        self.label_38.setStyleSheet("background-color:#09b4be;\n"
"border-radius:3px;\n"
"color:white;\n"
"")
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_4.addWidget(self.label_38)
        self.label_39 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_39.setFont(font)
        self.label_39.setStyleSheet("background-color:#09b4be;\n"
"border-radius:3px;\n"
"color:white;\n"
"")
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_4.addWidget(self.label_39)
        self.label_40 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_40.setFont(font)
        self.label_40.setStyleSheet("background-color:#09b4be;\n"
"border-radius:3px;\n"
"color:white;\n"
"")
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_4.addWidget(self.label_40)
        self.label_41 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_41.setFont(font)
        self.label_41.setStyleSheet("background-color:#09b4be;\n"
"border-radius:3px;\n"
"color:white;\n"
"")
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_4.addWidget(self.label_41)
        self.label_42 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_42.setFont(font)
        self.label_42.setStyleSheet("background-color:#09b4be;\n"
"border-radius:3px;\n"
"color:white;\n"
"")
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setObjectName("label_42")
        self.horizontalLayout_4.addWidget(self.label_42)
        self.label_43 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_43.setFont(font)
        self.label_43.setStyleSheet("background-color:#09b4be;\n"
"border-radius:3px;\n"
"color:white;\n"
"")
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_4.addWidget(self.label_43)
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(330, 240, 391, 91))
        self.label_11.setStyleSheet("background-color:#3d6787;\n"
"border-radius:6px")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.layoutWidget_3 = QtWidgets.QWidget(Form)
        self.layoutWidget_3.setGeometry(QtCore.QRect(340, 340, 371, 31))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_79 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_79.setFont(font)
        self.label_79.setStyleSheet("background-color:#38607e;\n"
"border-radius:6px;\n"
"color:white;\n"
"")
        self.label_79.setAlignment(QtCore.Qt.AlignCenter)
        self.label_79.setObjectName("label_79")
        self.horizontalLayout_10.addWidget(self.label_79)
        self.label_80 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_80.setFont(font)
        self.label_80.setStyleSheet("background-color:#38607e;\n"
"border-radius:6px;\n"
"color:white;\n"
"")
        self.label_80.setAlignment(QtCore.Qt.AlignCenter)
        self.label_80.setObjectName("label_80")
        self.horizontalLayout_10.addWidget(self.label_80)
        self.label_81 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_81.setFont(font)
        self.label_81.setStyleSheet("background-color:#38607e;\n"
"border-radius:6px;\n"
"color:white;\n"
"")
        self.label_81.setAlignment(QtCore.Qt.AlignCenter)
        self.label_81.setObjectName("label_81")
        self.horizontalLayout_10.addWidget(self.label_81)
        self.label_82 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_82.setFont(font)
        self.label_82.setStyleSheet("background-color:#38607e;\n"
"border-radius:6px;\n"
"color:white;\n"
"")
        self.label_82.setAlignment(QtCore.Qt.AlignCenter)
        self.label_82.setObjectName("label_82")
        self.horizontalLayout_10.addWidget(self.label_82)
        self.label_83 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_83.setFont(font)
        self.label_83.setStyleSheet("background-color:#38607e;\n"
"border-radius:6px;\n"
"color:white;\n"
"")
        self.label_83.setAlignment(QtCore.Qt.AlignCenter)
        self.label_83.setObjectName("label_83")
        self.horizontalLayout_10.addWidget(self.label_83)
        self.label_84 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_84.setFont(font)
        self.label_84.setStyleSheet("background-color:#38607e;\n"
"border-radius:6px;\n"
"color:white;\n"
"")
        self.label_84.setAlignment(QtCore.Qt.AlignCenter)
        self.label_84.setObjectName("label_84")
        self.horizontalLayout_10.addWidget(self.label_84)
        self.label_85 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_85.setFont(font)
        self.label_85.setStyleSheet("background-color:#38607e;\n"
"border-radius:6px;\n"
"color:white;\n"
"")
        self.label_85.setAlignment(QtCore.Qt.AlignCenter)
        self.label_85.setObjectName("label_85")
        self.horizontalLayout_10.addWidget(self.label_85)
        self.layoutWidget_4 = QtWidgets.QWidget(Form)
        self.layoutWidget_4.setGeometry(QtCore.QRect(340, 370, 371, 21))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_86 = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_86.setFont(font)
        self.label_86.setStyleSheet("background-color:#38607e;\n"
"border-radius:5px;\n"
"color:white;\n"
"")
        self.label_86.setAlignment(QtCore.Qt.AlignCenter)
        self.label_86.setObjectName("label_86")
        self.horizontalLayout_11.addWidget(self.label_86)
        self.label_87 = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_87.setFont(font)
        self.label_87.setStyleSheet("background-color:#38607e;\n"
"border-radius:5px;\n"
"color:white;\n"
"")
        self.label_87.setAlignment(QtCore.Qt.AlignCenter)
        self.label_87.setObjectName("label_87")
        self.horizontalLayout_11.addWidget(self.label_87)
        self.label_88 = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_88.setFont(font)
        self.label_88.setStyleSheet("background-color:#38607e;\n"
"border-radius:5px;\n"
"color:white;\n"
"")
        self.label_88.setAlignment(QtCore.Qt.AlignCenter)
        self.label_88.setObjectName("label_88")
        self.horizontalLayout_11.addWidget(self.label_88)
        self.label_89 = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_89.setFont(font)
        self.label_89.setStyleSheet("background-color:#38607e;\n"
"border-radius:5px;\n"
"color:white;\n"
"")
        self.label_89.setAlignment(QtCore.Qt.AlignCenter)
        self.label_89.setObjectName("label_89")
        self.horizontalLayout_11.addWidget(self.label_89)
        self.label_90 = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_90.setFont(font)
        self.label_90.setStyleSheet("background-color:#38607e;\n"
"border-radius:5px;\n"
"color:white;\n"
"")
        self.label_90.setAlignment(QtCore.Qt.AlignCenter)
        self.label_90.setObjectName("label_90")
        self.horizontalLayout_11.addWidget(self.label_90)
        self.label_91 = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_91.setFont(font)
        self.label_91.setStyleSheet("background-color:#38607e;\n"
"border-radius:5px;\n"
"color:white;\n"
"")
        self.label_91.setAlignment(QtCore.Qt.AlignCenter)
        self.label_91.setObjectName("label_91")
        self.horizontalLayout_11.addWidget(self.label_91)
        self.label_92 = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_92.setFont(font)
        self.label_92.setStyleSheet("background-color:#38607e;\n"
"border-radius:5px;\n"
"color:white;\n"
"")
        self.label_92.setAlignment(QtCore.Qt.AlignCenter)
        self.label_92.setObjectName("label_92")
        self.horizontalLayout_11.addWidget(self.label_92)
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(100, 370, 54, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("background-color:#9c58fe;\n"
"color:white;")
        self.label_14.setObjectName("label_14")
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(100, 350, 54, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("background-color:#9c58fe;\n"
"color:white;")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(40, 350, 41, 41))
        self.label_17.setStyleSheet("border-image: url(./weather_api/icon/风.png);\n"
"background-color:#9c58fe;")
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.label_21 = QtWidgets.QLabel(Form)
        self.label_21.setGeometry(QtCore.QRect(210, 370, 54, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("background-color:#9c58fe;\n"
"color:white;")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(Form)
        self.label_22.setGeometry(QtCore.QRect(160, 350, 41, 41))
        self.label_22.setStyleSheet("border-image: url(./weather_api/icon/空气质量.png);\n"
"background-color:#9c58fe;")
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(Form)
        self.label_23.setGeometry(QtCore.QRect(210, 350, 61, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("background-color:#9c58fe;\n"
"color:white;")
        self.label_23.setObjectName("label_23")
        self.weather_2 = QtWidgets.QGroupBox(Form)
        self.weather_2.setGeometry(QtCore.QRect(150, 280, 121, 61))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.weather_2.setFont(font)
        self.weather_2.setStyleSheet("background-color:#9c58fe;\n"
"border:0px")
        self.weather_2.setObjectName("weather_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.weather_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_18 = QtWidgets.QLabel(self.weather_2)
        self.label_18.setStyleSheet("\n"
"border-image: url(./weather_api/icon/温度 (1).png);\n"
"background-color:#9c58fe;")
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.gridLayout_5.addWidget(self.label_18, 0, 0, 2, 1)
        self.label_19 = QtWidgets.QLabel(self.weather_2)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("background-color:#9c58fe;\n"
"color:white;")
        self.label_19.setObjectName("label_19")
        self.gridLayout_5.addWidget(self.label_19, 0, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.weather_2)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("background-color:#9c58fe;\n"
"color:white;")
        self.label_20.setObjectName("label_20")
        self.gridLayout_5.addWidget(self.label_20, 1, 1, 1, 1)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(340, 90, 371, 21))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_24 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("background-color:#09b4be;\n"
"border-radius:3px;\n"
"color:white;\n"
"")
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_2.addWidget(self.label_24)
        self.label_25 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("background-color:#09b4be;\n"
"border-radius:3px;\n"
"color:white;\n"
"")
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_2.addWidget(self.label_25)
        self.label_26 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("background-color:#09b4be;\n"
"border-radius:3px;\n"
"color:white;\n"
"")
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_2.addWidget(self.label_26)
        self.label_33 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet("background-color:#09b4be;\n"
"border-radius:3px;\n"
"color:white;\n"
"")
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_2.addWidget(self.label_33)
        self.label_34 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("background-color:#09b4be;\n"
"border-radius:3px;\n"
"color:white;\n"
"")
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_2.addWidget(self.label_34)
        self.label_35 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("background-color:#09b4be;\n"
"border-radius:3px;\n"
"color:white;\n"
"")
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_2.addWidget(self.label_35)
        self.label_36 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_36.setFont(font)
        self.label_36.setStyleSheet("background-color:#09b4be;\n"
"border-radius:3px;\n"
"color:white;\n"
"")
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_2.addWidget(self.label_36)
        self.widget1 = QtWidgets.QWidget(Form)
        self.widget1.setGeometry(QtCore.QRect(340, 130, 371, 31))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_44 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_44.setFont(font)
        self.label_44.setStyleSheet("background-color:#38607e;\n"
"border-radius:6px;\n"
"color:white;\n"
"")
        self.label_44.setText("")
        self.label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44.setObjectName("label_44")
        self.horizontalLayout_5.addWidget(self.label_44)
        self.label_46 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_46.setFont(font)
        self.label_46.setStyleSheet("background-color:#38607e;\n"
"border-radius:6px;\n"
"color:white;\n"
"")
        self.label_46.setText("")
        self.label_46.setAlignment(QtCore.Qt.AlignCenter)
        self.label_46.setObjectName("label_46")
        self.horizontalLayout_5.addWidget(self.label_46)
        self.label_48 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_48.setFont(font)
        self.label_48.setStyleSheet("background-color:#38607e;\n"
"border-radius:6px;\n"
"color:white;\n"
"")
        self.label_48.setText("")
        self.label_48.setAlignment(QtCore.Qt.AlignCenter)
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_5.addWidget(self.label_48)
        self.label_50 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_50.setFont(font)
        self.label_50.setStyleSheet("background-color:#38607e;\n"
"border-radius:6px;\n"
"color:white;\n"
"")
        self.label_50.setText("")
        self.label_50.setAlignment(QtCore.Qt.AlignCenter)
        self.label_50.setObjectName("label_50")
        self.horizontalLayout_5.addWidget(self.label_50)
        self.label_52 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_52.setFont(font)
        self.label_52.setStyleSheet("background-color:#38607e;\n"
"border-radius:6px;\n"
"color:white;\n"
"")
        self.label_52.setText("")
        self.label_52.setAlignment(QtCore.Qt.AlignCenter)
        self.label_52.setObjectName("label_52")
        self.horizontalLayout_5.addWidget(self.label_52)
        self.label_54 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_54.setFont(font)
        self.label_54.setStyleSheet("background-color:#38607e;\n"
"border-radius:6px;\n"
"color:white;\n"
"")
        self.label_54.setText("")
        self.label_54.setAlignment(QtCore.Qt.AlignCenter)
        self.label_54.setObjectName("label_54")
        self.horizontalLayout_5.addWidget(self.label_54)
        self.label_56 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_56.setFont(font)
        self.label_56.setStyleSheet("background-color:#38607e;\n"
"border-radius:6px;\n"
"color:white;\n"
"")
        self.label_56.setText("")
        self.label_56.setAlignment(QtCore.Qt.AlignCenter)
        self.label_56.setObjectName("label_56")
        self.horizontalLayout_5.addWidget(self.label_56)
        self.widget2 = QtWidgets.QWidget(Form)
        self.widget2.setGeometry(QtCore.QRect(340, 160, 371, 21))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_45 = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_45.setFont(font)
        self.label_45.setStyleSheet("background-color:#38607e;\n"
"border-radius:5px;\n"
"color:white;\n"
"")
        self.label_45.setAlignment(QtCore.Qt.AlignCenter)
        self.label_45.setObjectName("label_45")
        self.horizontalLayout_6.addWidget(self.label_45)
        self.label_47 = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_47.setFont(font)
        self.label_47.setStyleSheet("background-color:#38607e;\n"
"border-radius:5px;\n"
"color:white;\n"
"")
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName("label_47")
        self.horizontalLayout_6.addWidget(self.label_47)
        self.label_49 = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_49.setFont(font)
        self.label_49.setStyleSheet("background-color:#38607e;\n"
"border-radius:5px;\n"
"color:white;\n"
"")
        self.label_49.setAlignment(QtCore.Qt.AlignCenter)
        self.label_49.setObjectName("label_49")
        self.horizontalLayout_6.addWidget(self.label_49)
        self.label_51 = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_51.setFont(font)
        self.label_51.setStyleSheet("background-color:#38607e;\n"
"border-radius:5px;\n"
"color:white;\n"
"")
        self.label_51.setAlignment(QtCore.Qt.AlignCenter)
        self.label_51.setObjectName("label_51")
        self.horizontalLayout_6.addWidget(self.label_51)
        self.label_53 = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_53.setFont(font)
        self.label_53.setStyleSheet("background-color:#38607e;\n"
"border-radius:5px;\n"
"color:white;\n"
"")
        self.label_53.setAlignment(QtCore.Qt.AlignCenter)
        self.label_53.setObjectName("label_53")
        self.horizontalLayout_6.addWidget(self.label_53)
        self.label_55 = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_55.setFont(font)
        self.label_55.setStyleSheet("background-color:#38607e;\n"
"border-radius:5px;\n"
"color:white;\n"
"")
        self.label_55.setAlignment(QtCore.Qt.AlignCenter)
        self.label_55.setObjectName("label_55")
        self.horizontalLayout_6.addWidget(self.label_55)
        self.label_57 = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_57.setFont(font)
        self.label_57.setStyleSheet("background-color:#38607e;\n"
"border-radius:5px;\n"
"color:white;\n"
"")
        self.label_57.setAlignment(QtCore.Qt.AlignCenter)
        self.label_57.setObjectName("label_57")
        self.horizontalLayout_6.addWidget(self.label_57)
        self.widget3 = QtWidgets.QWidget(Form)
        self.widget3.setGeometry(QtCore.QRect(340, 200, 371, 31))
        self.widget3.setObjectName("widget3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget3)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_58 = QtWidgets.QLabel(self.widget3)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_58.setFont(font)
        self.label_58.setStyleSheet("background-color:#78b700;\n"
"border-radius:6px;\n"
"color:white;\n"
"")
        self.label_58.setAlignment(QtCore.Qt.AlignCenter)
        self.label_58.setObjectName("label_58")
        self.horizontalLayout_7.addWidget(self.label_58)
        self.label_59 = QtWidgets.QLabel(self.widget3)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_59.setFont(font)
        self.label_59.setStyleSheet("background-color:#feb914;\n"
"border-radius:6px;\n"
"color:white;\n"
"")
        self.label_59.setAlignment(QtCore.Qt.AlignCenter)
        self.label_59.setObjectName("label_59")
        self.horizontalLayout_7.addWidget(self.label_59)
        self.label_60 = QtWidgets.QLabel(self.widget3)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_60.setFont(font)
        self.label_60.setStyleSheet("background-color:#78b700;\n"
"border-radius:6px;\n"
"color:white;\n"
"")
        self.label_60.setAlignment(QtCore.Qt.AlignCenter)
        self.label_60.setObjectName("label_60")
        self.horizontalLayout_7.addWidget(self.label_60)
        self.label_61 = QtWidgets.QLabel(self.widget3)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_61.setFont(font)
        self.label_61.setStyleSheet("background-color:#78b700;\n"
"border-radius:6px;\n"
"color:white;\n"
"")
        self.label_61.setAlignment(QtCore.Qt.AlignCenter)
        self.label_61.setObjectName("label_61")
        self.horizontalLayout_7.addWidget(self.label_61)
        self.label_62 = QtWidgets.QLabel(self.widget3)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_62.setFont(font)
        self.label_62.setStyleSheet("background-color:#78b700;\n"
"border-radius:6px;\n"
"color:white;\n"
"")
        self.label_62.setAlignment(QtCore.Qt.AlignCenter)
        self.label_62.setObjectName("label_62")
        self.horizontalLayout_7.addWidget(self.label_62)
        self.label_63 = QtWidgets.QLabel(self.widget3)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_63.setFont(font)
        self.label_63.setStyleSheet("background-color:#feb914;\n"
"border-radius:6px;\n"
"color:white;\n"
"")
        self.label_63.setAlignment(QtCore.Qt.AlignCenter)
        self.label_63.setObjectName("label_63")
        self.horizontalLayout_7.addWidget(self.label_63)
        self.label_64 = QtWidgets.QLabel(self.widget3)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_64.setFont(font)
        self.label_64.setStyleSheet("background-color:#feb914;\n"
"border-radius:6px;\n"
"color:white;\n"
"")
        self.label_64.setAlignment(QtCore.Qt.AlignCenter)
        self.label_64.setObjectName("label_64")
        self.horizontalLayout_7.addWidget(self.label_64)
        self.widget4 = QtWidgets.QWidget(Form)
        self.widget4.setGeometry(QtCore.QRect(340, 250, 371, 31))
        self.widget4.setObjectName("widget4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget4)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_65 = QtWidgets.QLabel(self.widget4)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_65.setFont(font)
        self.label_65.setStyleSheet("background-color:#dbb70e;\n"
"border-radius:6px;\n"
"color:white;\n"
"")
        self.label_65.setAlignment(QtCore.Qt.AlignCenter)
        self.label_65.setObjectName("label_65")
        self.horizontalLayout_8.addWidget(self.label_65)
        self.label_66 = QtWidgets.QLabel(self.widget4)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_66.setFont(font)
        self.label_66.setStyleSheet("background-color:#dbb70e;\n"
"border-radius:6px;\n"
"color:white;\n"
"")
        self.label_66.setAlignment(QtCore.Qt.AlignCenter)
        self.label_66.setObjectName("label_66")
        self.horizontalLayout_8.addWidget(self.label_66)
        self.label_67 = QtWidgets.QLabel(self.widget4)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_67.setFont(font)
        self.label_67.setStyleSheet("background-color:#dbb70e;\n"
"border-radius:6px;\n"
"color:white;\n"
"")
        self.label_67.setAlignment(QtCore.Qt.AlignCenter)
        self.label_67.setObjectName("label_67")
        self.horizontalLayout_8.addWidget(self.label_67)
        self.label_68 = QtWidgets.QLabel(self.widget4)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_68.setFont(font)
        self.label_68.setStyleSheet("background-color:#dbb70e;\n"
"border-radius:6px;\n"
"color:white;\n"
"")
        self.label_68.setAlignment(QtCore.Qt.AlignCenter)
        self.label_68.setObjectName("label_68")
        self.horizontalLayout_8.addWidget(self.label_68)
        self.label_69 = QtWidgets.QLabel(self.widget4)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_69.setFont(font)
        self.label_69.setStyleSheet("background-color:#dbb70e;\n"
"border-radius:6px;\n"
"color:white;\n"
"")
        self.label_69.setAlignment(QtCore.Qt.AlignCenter)
        self.label_69.setObjectName("label_69")
        self.horizontalLayout_8.addWidget(self.label_69)
        self.label_70 = QtWidgets.QLabel(self.widget4)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_70.setFont(font)
        self.label_70.setStyleSheet("background-color:#dbb70e;\n"
"border-radius:6px;\n"
"color:white;\n"
"")
        self.label_70.setAlignment(QtCore.Qt.AlignCenter)
        self.label_70.setObjectName("label_70")
        self.horizontalLayout_8.addWidget(self.label_70)
        self.label_71 = QtWidgets.QLabel(self.widget4)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_71.setFont(font)
        self.label_71.setStyleSheet("background-color:#dbb70e;\n"
"border-radius:6px;\n"
"color:white;\n"
"")
        self.label_71.setAlignment(QtCore.Qt.AlignCenter)
        self.label_71.setObjectName("label_71")
        self.horizontalLayout_8.addWidget(self.label_71)
        self.widget5 = QtWidgets.QWidget(Form)
        self.widget5.setGeometry(QtCore.QRect(340, 290, 371, 31))
        self.widget5.setObjectName("widget5")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget5)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_72 = QtWidgets.QLabel(self.widget5)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_72.setFont(font)
        self.label_72.setStyleSheet("background-color:#4287ba;\n"
"border-radius:6px;\n"
"color:white;\n"
"")
        self.label_72.setAlignment(QtCore.Qt.AlignCenter)
        self.label_72.setObjectName("label_72")
        self.horizontalLayout_9.addWidget(self.label_72)
        self.label_73 = QtWidgets.QLabel(self.widget5)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_73.setFont(font)
        self.label_73.setStyleSheet("background-color:#4287ba;\n"
"border-radius:6px;\n"
"color:white;\n"
"")
        self.label_73.setAlignment(QtCore.Qt.AlignCenter)
        self.label_73.setObjectName("label_73")
        self.horizontalLayout_9.addWidget(self.label_73)
        self.label_74 = QtWidgets.QLabel(self.widget5)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_74.setFont(font)
        self.label_74.setStyleSheet("background-color:#4287ba;\n"
"border-radius:6px;\n"
"color:white;\n"
"")
        self.label_74.setAlignment(QtCore.Qt.AlignCenter)
        self.label_74.setObjectName("label_74")
        self.horizontalLayout_9.addWidget(self.label_74)
        self.label_75 = QtWidgets.QLabel(self.widget5)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_75.setFont(font)
        self.label_75.setStyleSheet("background-color:#4287ba;\n"
"border-radius:6px;\n"
"color:white;\n"
"")
        self.label_75.setAlignment(QtCore.Qt.AlignCenter)
        self.label_75.setObjectName("label_75")
        self.horizontalLayout_9.addWidget(self.label_75)
        self.label_76 = QtWidgets.QLabel(self.widget5)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_76.setFont(font)
        self.label_76.setStyleSheet("background-color:#4287ba;\n"
"border-radius:6px;\n"
"color:white;\n"
"")
        self.label_76.setAlignment(QtCore.Qt.AlignCenter)
        self.label_76.setObjectName("label_76")
        self.horizontalLayout_9.addWidget(self.label_76)
        self.label_77 = QtWidgets.QLabel(self.widget5)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_77.setFont(font)
        self.label_77.setStyleSheet("background-color:#4287ba;\n"
"border-radius:6px;\n"
"color:white;\n"
"")
        self.label_77.setAlignment(QtCore.Qt.AlignCenter)
        self.label_77.setObjectName("label_77")
        self.horizontalLayout_9.addWidget(self.label_77)
        self.label_78 = QtWidgets.QLabel(self.widget5)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_78.setFont(font)
        self.label_78.setStyleSheet("background-color:#4287ba;\n"
"border-radius:6px;\n"
"color:white;\n"
"")
        self.label_78.setAlignment(QtCore.Qt.AlignCenter)
        self.label_78.setObjectName("label_78")
        self.horizontalLayout_9.addWidget(self.label_78)
        self.weather_1 = QtWidgets.QGroupBox(Form)
        self.weather_1.setGeometry(QtCore.QRect(30, 280, 121, 61))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.weather_1.setFont(font)
        self.weather_1.setStyleSheet("background-color:#9c58fe;\n"
"border:0px")
        self.weather_1.setObjectName("weather_1")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.weather_1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_10 = QtWidgets.QLabel(self.weather_1)
        self.label_10.setStyleSheet("border-image: url(weather_api/icon/湿度.png);\n"
"background-color:#9c58fe;")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 0, 0, 2, 1)
        self.label_12 = QtWidgets.QLabel(self.weather_1)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("background-color:#9c58fe;\n"
"color:white;")
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 0, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.weather_1)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("background-color:#9c58fe;\n"
"color:white;")
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 1, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lineEdit.setPlaceholderText(_translate("Form", "请输入你的城市"))
        self.label_3.setText(_translate("Form", f"{list1[0]['city_name']}"))
        self.label_4.setText(_translate("Form", f"{list1[0]['temp_ti'].split('°C')[0]}"))
        self.label_5.setText(_translate("Form", f"{list1[0]['weather_text']}"))
        self.label_6.setText(_translate("Form", f"{list1[1][0]['min_temp']}°C -{list1[1][0]['max_temp']}°C"))
        self.label_7.setText(_translate("Form", f"{list1[0]['msg']}"))
        self.label_9.setText(_translate("Form", f"{show_today_date()}"))

        weekdays = ['周一', '周二', '周三', '周四', '周五', '周六', '周日']
        num = show_today_week()
        self.label_37.setText(_translate("Form", f"{weekdays[num]}"))
        self.label_38.setText(_translate("Form", f"{weekdays[(num+1)%7]}"))
        self.label_39.setText(_translate("Form", f"{weekdays[(num+2)%7]}"))
        self.label_40.setText(_translate("Form", f"{weekdays[(num+3)%7]}"))
        self.label_41.setText(_translate("Form", f"{weekdays[(num+4)%7]}"))
        self.label_42.setText(_translate("Form", f"{weekdays[(num+5)%7]}"))
        self.label_43.setText(_translate("Form", f"{weekdays[(num+6)%7]}"))
        self.label_79.setText(_translate("Form", f"{list1[1][0]['windDirDay']}"))
        self.label_80.setText(_translate("Form", f"{list1[1][1]['windDirDay']}"))
        self.label_81.setText(_translate("Form", f"{list1[1][2]['windDirDay']}"))
        self.label_82.setText(_translate("Form", f"{list1[1][3]['windDirDay']}"))
        self.label_83.setText(_translate("Form", f"{list1[1][4]['windDirDay']}"))
        self.label_84.setText(_translate("Form", f"{list1[1][5]['windDirDay']}"))
        self.label_85.setText(_translate("Form", f"{list1[1][6]['windDirDay']}"))
        self.label_86.setText(_translate("Form", f"{list1[1][0]['windSpeedDay']}"))
        self.label_87.setText(_translate("Form", f"{list1[1][1]['windSpeedDay']}"))
        self.label_88.setText(_translate("Form", f"{list1[1][2]['windSpeedDay']}"))
        self.label_89.setText(_translate("Form", f"{list1[1][3]['windSpeedDay']}"))
        self.label_90.setText(_translate("Form", f"{list1[1][4]['windSpeedDay']}"))
        self.label_91.setText(_translate("Form", f"{list1[1][5]['windSpeedDay']}"))
        self.label_92.setText(_translate("Form", f"{list1[1][6]['windSpeedDay']}"))
        self.label_14.setText(_translate("Form", f"{list1[1][0]['windSpeedDay']}"))
        self.label_16.setText(_translate("Form", f"{list1[1][0]['windDirDay']}"))
        self.label_21.setText(_translate("Form", f"{list1[0]['air_aqi']}"))
        self.label_23.setText(_translate("Form", "空气质量"))
        self.label_19.setText(_translate("Form", "体感温度"))
        self.label_20.setText(_translate("Form", f"{list1[0]['temp_ti']}"))

        data_list = []
        data_list = get_week_dates()

        self.label_24.setText(_translate("Form", f"{data_list[0]}"))
        self.label_25.setText(_translate("Form", f"{data_list[1]}"))
        self.label_26.setText(_translate("Form", f"{data_list[2]}"))
        self.label_33.setText(_translate("Form", f"{data_list[3]}"))
        self.label_34.setText(_translate("Form", f"{data_list[4]}"))
        self.label_35.setText(_translate("Form", f"{data_list[5]}"))
        self.label_36.setText(_translate("Form", f"{data_list[6]}"))
        self.label_45.setText(_translate("Form", f"{list1[0]['weather_text']}"))
        self.label_47.setText(_translate("Form", f"{list1[1][1]['weather_day']}"))
        self.label_49.setText(_translate("Form", f"{list1[1][2]['weather_day']}"))
        self.label_51.setText(_translate("Form", f"{list1[1][3]['weather_day']}"))
        self.label_53.setText(_translate("Form", f"{list1[1][4]['weather_day']}"))
        self.label_55.setText(_translate("Form", f"{list1[1][5]['weather_day']}"))
        self.label_57.setText(_translate("Form", f"{list1[1][6]['weather_day']}"))
        self.label_58.setText(_translate("Form", f"{list1[0]['air_aqi'].split('(')[1].split(')')[0]}"))
        self.label_59.setText(_translate("Form", "良"))
        self.label_60.setText(_translate("Form", "优"))
        self.label_61.setText(_translate("Form", "优"))
        self.label_62.setText(_translate("Form", "优"))
        self.label_63.setText(_translate("Form", "良"))
        self.label_64.setText(_translate("Form", "良"))
        self.label_65.setText(_translate("Form", f"{list1[1][0]['max_temp']}°C"))
        self.label_66.setText(_translate("Form", f"{list1[1][0]['min_temp']}°C"))
        self.label_67.setText(_translate("Form", f"{list1[1][1]['max_temp']}°C"))
        self.label_68.setText(_translate("Form", f"{list1[1][1]['min_temp']}°C"))
        self.label_69.setText(_translate("Form", f"{list1[1][2]['max_temp']}°C"))
        self.label_70.setText(_translate("Form", f"{list1[1][2]['min_temp']}°C"))
        self.label_71.setText(_translate("Form", f"{list1[1][3]['max_temp']}°C"))
        self.label_72.setText(_translate("Form", f"{list1[1][3]['min_temp']}°C"))
        self.label_73.setText(_translate("Form", f"{list1[1][4]['max_temp']}°C"))
        self.label_74.setText(_translate("Form", f"{list1[1][4]['min_temp']}°C"))
        self.label_75.setText(_translate("Form", f"{list1[1][5]['max_temp']}°C"))
        self.label_76.setText(_translate("Form", f"{list1[1][5]['min_temp']}°C"))
        self.label_77.setText(_translate("Form", f"{list1[1][6]['max_temp']}°C"))
        self.label_78.setText(_translate("Form", f"{list1[1][6]['min_temp']}°C"))
        self.label_12.setText(_translate("Form", "湿度"))
        self.label_13.setText(_translate("Form", f"{list1[0]['humidity']}%"))

        msg = f"今天天气：{list1[0]['weather_text']} 体感温度{list1[0]['temp_ti'].split('°C')[0]}摄氏度 。主人，今日{list1[0]['msg']}"
        self.voice_thread = VoiceThread(msg)
        self.voice_thread.finished.connect(self.retranslateUi)
        self.voice_thread.start()




class weatherWindow(QWidget, Ui_Form):
    def __init__(self):
        super().__init__()
        self.setWindowTitle('天气预报')
        self.setupUi(self)

    def closeEvent(self, event):
         event.ignore()  # 忽略默认的关闭事件
         self.hide()  # 隐藏当前窗口，而不是关闭






from PyQt5.QtCore import QDate,QLocale
from datetime import datetime

def show_today_date():
    # 获取当前日期时间对象
    today_date_time = datetime.now()

    # 提取日期信息
    year = today_date_time.year
    month = today_date_time.month
    day = today_date_time.day

    # 格式化月份和日期为两位数形式
    formatted_month = f"{month:02d}"
    formatted_day = f"{day:02d}"


    # 获取今天是星期几（0表示星期一，6表示星期日）
    weekday_num = today_date_time.weekday()
    weekdays = ['星期一', '星期二', '星期三', '星期四', '星期五', '星期六', '星期日']
    weekday = weekdays[weekday_num]

    # 格式化输出日期
    formatted_date = f"{year}/{formatted_month}/{formatted_day} {weekday}"

    return formatted_date

def show_today_week():
# 获取当前日期时间对象
    today_date_time = datetime.now()
    weekday_num = today_date_time.weekday()
    return weekday_num

from datetime import datetime, timedelta

def get_week_dates():
    # 获取当前日期时间对象
    today_date_time = datetime.now()

    # 初始化日期列表，用于存放今天及今天之后七天的日期字符串
    week_dates = []

    # 添加今天日期
    week_dates.append(today_date_time.strftime("%m/%d"))

    # 添加今天之后七天的日期
    for i in range(1, 8):
        next_date = today_date_time + timedelta(days=i)
        week_dates.append(next_date.strftime("%m/%d"))

    return week_dates






if __name__ == "__main__":
# 调用函数获取今天及今天之后七天日期，并存放在列表中

    # import sys
    # app = QtWidgets.QApplication(sys.argv)
    # Form = QtWidgets.QWidget()
    # ui = Ui_Form()
    # ui.setupUi(Form)
    # Form.show()
    # sys.exit(app.exec_())
        app = QApplication([])
        main_window = weatherWindow()
        main_window.show()
        app.exec_()