# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zhuye.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



import re
from PyQt5.QtWidgets import QApplication, QWidget, QMessageBox
from PyQt5 import QtCore, QtGui, QtWidgets
import base64
import os
import logging
import speech_recognition as sr
import pyttsx3
import json
import requests
import time

def get_access_token():
    url = "https://aip.baidubce.com/oauth/2.0/token?grant_type=client_credentials&client_id=e1adkIbaxkTYFNdUOeACBRP6&client_secret=UIlHoGkGHisD7dY3PKZScN1Zy234U21Y"
    payload = json.dumps("")
    headers = {'Content-Type': 'application/json', 'Accept': 'application/json'}
    response = requests.request("POST", url, headers=headers, data=payload)
    return response.json().get("access_token")







def speech_recognition():
    from zhuochong2333.main import process_audio, wenxin
    message = process_audio()
    return message





class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(973, 690)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 40, 231, 141))
        self.label.setStyleSheet("background-color: #a8ffff;\n"
"border: 2px solid #7e8490;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 190, 231, 321))
        self.label_2.setStyleSheet("\n"
"border: 2px solid #7e8490;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(20, 530, 231, 131))
        self.label_3.setStyleSheet("\n"
"border: 2px solid #7e8490;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(290, 20, 641, 651))
        self.label_4.setStyleSheet("border-radius:3px;\n"
"color:#7e8490;\n"
"border: 3px solid #7e8490;")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(30, 540, 121, 51))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("border: 2px solid #d0d8df")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(30, 600, 121, 51))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("border: 2px solid #d0d8df;")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(30, 210, 211, 51))
        self.label_7.setStyleSheet("border: 2px solid #d0d8df")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(30, 270, 211, 51))
        self.label_8.setStyleSheet("border: 2px solid #d0d8df")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(30, 330, 211, 51))
        self.label_9.setStyleSheet("border: 2px solid #d0d8df")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(30, 390, 211, 51))
        self.label_10.setStyleSheet("border: 2px solid #d0d8df")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(30, 450, 211, 51))
        self.label_11.setStyleSheet("border: 2px solid #d0d8df")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(310, 40, 451, 131))
        self.label_12.setStyleSheet("border: 2px solid #d0d8df")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(790, 50, 121, 51))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("border: 2px solid #0a0909")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(790, 110, 121, 51))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("border: 2px solid #0a0909")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.pushButton2_clicked)



        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(310, 190, 601, 461))
        self.label_13.setStyleSheet("border: 3px solid #0a0909")
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(120, 220, 111, 31))
        self.pushButton_3.setStyleSheet("background-color:#38a9ff;\n"
"border: none")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(120, 280, 111, 31))
        self.pushButton_4.setStyleSheet("background-color:#38a9ff;\n"
"border: none")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(120, 340, 111, 31))
        self.pushButton_5.setStyleSheet("background-color:#38a9ff;\n"
"border: none")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(120, 400, 111, 31))
        self.pushButton_6.setStyleSheet("background-color:#38a9ff;\n"
"border: none")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(Form)
        self.pushButton_7.setGeometry(QtCore.QRect(120, 460, 111, 31))
        self.pushButton_7.setStyleSheet("background-color:#38a9ff;\n"
"border: none")
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(50, 210, 61, 51))
        self.label_14.setStyleSheet("border-image: url(:/icon/DND_mode.png);")
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(50, 270, 61, 51))
        self.label_15.setStyleSheet("border-image: url(:/icon/DND_mode.png);")
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(50, 330, 61, 51))
        self.label_16.setStyleSheet("border-image: url(:/icon/DND_mode.png);")
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(50, 390, 61, 51))
        self.label_17.setStyleSheet("border-image: url(:/icon/DND_mode.png);")
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setGeometry(QtCore.QRect(50, 450, 61, 51))
        self.label_18.setStyleSheet("border-image: url(:/icon/DND_mode.png);")
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.pushButton_8 = QtWidgets.QPushButton(Form)
        self.pushButton_8.setGeometry(QtCore.QRect(160, 570, 75, 51))
        self.pushButton_8.setStyleSheet("background-color:#38a9ff;\n"
"border: none")
        self.pushButton_8.setObjectName("pushButton_8")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_5.setText(_translate("Form", "目前版本:V1.0"))
        self.label_6.setText(_translate("Form", "本系统由大学生开发"))
        self.pushButton.setText(_translate("Form", "产品解释"))
        self.pushButton_2.setText(_translate("Form", "语音调用"))
        self.pushButton_3.setText(_translate("Form", "文本翻译"))
        self.pushButton_4.setText(_translate("Form", "类型转换"))
        self.pushButton_5.setText(_translate("Form", "文件传输"))
        self.pushButton_6.setText(_translate("Form", "图片识别"))
        self.pushButton_7.setText(_translate("Form", "文本对话"))
        self.pushButton_8.setText(_translate("Form", "软件反馈"))


    def pushButton2_clicked(self):
        print('语音对话被点击了')
        message = '正在语音识别，请说出你想说的话'
        self.label_12.setText(message)

        message = speech_recognition()
        print(message)

        # from RumiaPet_main.TTS_bachongshenzi import tts_and_play

        self.label_12.setText(message)

        headers = {'Content-Type': 'application/json'}
        url = "https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/chat/completions_pro?access_token=" + str(
            get_access_token())
        payload = json.dumps({"messages": [{"role": "user", "content": f'{message}'}], "stream": True})
        response = requests.request("POST", url, headers=headers, data=payload, stream=True)
        for line in response.iter_lines():
            if line:
                data = json.loads(line.decode("utf-8").replace("data: ", ""))
                msg = data["result"]
                print(msg)
                self.label_12.setText(msg)

                import pyttsx3
                engine = pyttsx3.init()
                engine.say(msg)
                engine.runAndWait()

                # tts_and_play(msg)




    def closeEvent(self, event):
        event.ignore()  # 忽略默认的关闭事件
        self.hide()  # 隐藏当前窗口，而不是关闭



class BangongWindow(QWidget, Ui_Form):
    def __init__(self):
        super().__init__()
        self.setWindowTitle('注册页面')
        self.setupUi(self)


if __name__ == "__main__":


    app = QApplication([])
    main_window = BangongWindow()
    main_window.show()
    app.exec_()

    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
